version: "3"

services:
  server:
    command: "npm run dev"
    # image: registry.heroku.com/beer-site-container/web:latest
    build: ./server
    ports:
      - "3000:3000"
    environment:
      HOST_URL: ${MY_HOST}
    volumes:
      - ./public:/beersite/public

  # public:
  #   build: ./public
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - server
  #   environment:
  #     HOST_URL: ${MY_HOST}
