version: "3"

services:
  server:
    command: "npm run dev"
    # image: registry.heroku.com/beer-site-container/web:latest
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      HOST_URL: ${MY_HOST}
    volumes:
      - ./public:/beersite/public

  api:
    image: registry.heroku.com/beer-site-api/web:latest
    # build: ./api
    ports:
      - "7000:7000"
    environment:
      HOST_URL: ${MY_HOST}
