version: "3.3"

services:
  server:
    command: "npm run dev"
    # image: johangludjensen/beersite_server:latest
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - public
    volumes:
      - ./public:/beersite/public

  public:
    build: ./public
    ports:
      - "5000:5000"
